/**
 * Dead Letter Queue Tests
 *
 * Test coverage for:
 * - Storing failed operations
 * - Persisting to disk (dlq.jsonl)
 * - CLI operations: list, replay, purge
 * - Alert on large queue size
 */

import { unlink, readFile, mkdir, writeFile, readdir, stat, rmdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  createDeadLetterQueue,
  type DeadLetterQueueService,
  type DLQEntry,
} from "../dead-letter-queue.js";

// Input type for enqueue (excludes fields generated by the service)
type DLQEntryInput = Omit<DLQEntry, "errorId" | "failedAt"> & {
  originalError: Error | { message: string; name: string };
};

describe("DeadLetterQueue", () => {
  let dlq: DeadLetterQueueService;
  let dlqPath: string;

  beforeEach(async () => {
    // Create temp directory for test DLQ files
    const tempDir = join(tmpdir(), `ao-dlq-test-${Date.now()}`);
    await mkdir(tempDir, { recursive: true });
    dlqPath = join(tempDir, "dlq.jsonl");

    // Create DLQ service
    dlq = createDeadLetterQueue({
      dlqPath,
      alertThreshold: 1000,
    });
  });

  afterEach(async () => {
    // Cleanup
    if (existsSync(dlqPath)) {
      await unlink(dlqPath);
    }
  });

  describe("enqueue", () => {
    it("should store a failed operation", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const errorId = await dlq.enqueue(entry);

      expect(errorId).toBeDefined();
      expect(typeof errorId).toBe("string");

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(1);
    });

    it("should persist entry to disk", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      await dlq.enqueue(entry);

      // Verify file exists and contains entry
      expect(existsSync(dlqPath)).toBe(true);
      const content = await readFile(dlqPath, "utf-8");
      const lines = content.trim().split("\n");
      expect(lines.length).toBe(1);

      const parsed = JSON.parse(lines[0]) as DLQEntry;
      expect(parsed.operation).toBe("bmad_sync");
      expect(parsed.failureReason).toBe("Connection timeout");
    });

    it("should generate unique error IDs", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const id1 = await dlq.enqueue(entry);
      const id2 = await dlq.enqueue(entry);

      expect(id1).not.toBe(id2);
    });

    it("should store timestamp when enqueued", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const before = Date.now();
      await dlq.enqueue(entry);
      const after = Date.now();

      const list = await dlq.list();
      expect(list.length).toBe(1);

      const failedAt = new Date(list[0].failedAt).getTime();
      expect(failedAt).toBeGreaterThanOrEqual(before);
      expect(failedAt).toBeLessThanOrEqual(after);
    });
  });

  describe("list", () => {
    it("should return all failed operations", async () => {
      const entry1: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const entry2: DLQEntryInput = {
        operation: "event_publish",
        payload: { eventType: "story.update" },
        failureReason: "Service unavailable",
        retryCount: 3,
        originalError: new Error("503"),
      };

      await dlq.enqueue(entry1);
      await dlq.enqueue(entry2);

      const list = await dlq.list();
      expect(list.length).toBe(2);
      expect(list[0].operation).toBe("bmad_sync");
      expect(list[1].operation).toBe("event_publish");
    });

    it("should return empty array when no entries", async () => {
      const list = await dlq.list();
      expect(list).toEqual([]);
    });

    it("should include all entry fields", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1", data: "test" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      await dlq.enqueue(entry);
      const list = await dlq.list();

      expect(list[0]).toMatchObject({
        errorId: expect.any(String),
        operation: "bmad_sync",
        payload: { storyId: "1-1", data: "test" },
        failureReason: "Connection timeout",
        retryCount: 5,
        failedAt: expect.any(String),
      });
    });
  });

  describe("get", () => {
    it("should return entry by error ID", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const errorId = await dlq.enqueue(entry);
      const retrieved = await dlq.get(errorId);

      expect(retrieved).toBeDefined();
      expect(retrieved?.operation).toBe("bmad_sync");
    });

    it("should return null for non-existent error ID", async () => {
      const retrieved = await dlq.get("non-existent-id");
      expect(retrieved).toBeNull();
    });
  });

  describe("replay", () => {
    it("should execute operation and remove from DLQ on success", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);
      let executed = false;
      let receivedPayload: unknown = null;

      const replayFn = async (payload: unknown) => {
        executed = true;
        receivedPayload = payload;
        return "success";
      };

      const result = await dlq.replay(errorId, replayFn);

      expect(result).toBe("success");
      expect(executed).toBe(true);
      expect(receivedPayload).toEqual({ value: 42 });

      // Entry should be removed from DLQ
      const retrieved = await dlq.get(errorId);
      expect(retrieved).toBeNull();

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(0);
    });

    it("should keep entry in DLQ on replay failure", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);

      const replayFn = async () => {
        throw new Error("Replay failed");
      };

      const result = await dlq.replay(errorId, replayFn);
      expect(result).toBeNull(); // Replay failure returns null

      // Entry should still be in DLQ
      const retrieved = await dlq.get(errorId);
      expect(retrieved).toBeDefined();

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(1);
    });

    it("should return null for non-existent error ID", async () => {
      const replayFn = async () => "success";
      const result = await dlq.replay("non-existent-id", replayFn);
      expect(result).toBeNull();
    });

    it("should bypass circuit breaker when replaying", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);

      let bypassedCircuitBreaker = false;
      const replayFn = async () => {
        bypassedCircuitBreaker = true;
        return "success";
      };

      await dlq.replay(errorId, replayFn);

      expect(bypassedCircuitBreaker).toBe(true);
    });
  });

  describe("purge", () => {
    it("should remove entries older than threshold", async () => {
      const oldEntry: DLQEntryInput = {
        operation: "old_operation",
        payload: {},
        failureReason: "Old failure",
        retryCount: 1,
        originalError: new Error("Old"),
      };

      await dlq.enqueue(oldEntry);

      // Wait longer to ensure time difference
      await new Promise((resolve) => setTimeout(resolve, 100));

      const newEntry: DLQEntryInput = {
        operation: "new_operation",
        payload: {},
        failureReason: "New failure",
        retryCount: 1,
        originalError: new Error("New"),
      };

      await dlq.enqueue(newEntry);

      // Purge entries older than 50ms (should keep only new entry)
      const purged = await dlq.purge(50);

      expect(purged).toBe(1);

      const list = await dlq.list();
      expect(list.length).toBe(1);
      expect(list[0].operation).toBe("new_operation");
    });

    it("should return 0 when no entries to purge", async () => {
      const purged = await dlq.purge(1000);
      expect(purged).toBe(0);
    });

    it("should remove all entries if all are old", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: {},
        failureReason: "Test failure",
        retryCount: 1,
        originalError: new Error("Test"),
      };

      await dlq.enqueue(entry);

      // Wait to ensure entry is old enough
      await new Promise((resolve) => setTimeout(resolve, 100));

      const purged = await dlq.purge(50);

      expect(purged).toBe(1);

      const list = await dlq.list();
      expect(list.length).toBe(0);
    });
  });

  describe("getStats", () => {
    it("should return statistics about DLQ", async () => {
      const entry1: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const entry2: DLQEntryInput = {
        operation: "event_publish",
        payload: { eventType: "story.update" },
        failureReason: "Service unavailable",
        retryCount: 3,
        originalError: new Error("503"),
      };

      await dlq.enqueue(entry1);
      await dlq.enqueue(entry2);

      const stats = await dlq.getStats();

      expect(stats.totalEntries).toBe(2);
      expect(stats.byOperation).toEqual({
        bmad_sync: 1,
        event_publish: 1,
      });
      expect(stats.oldestEntry).toBeDefined();
      expect(stats.newestEntry).toBeDefined();
    });

    it("should return zero stats when empty", async () => {
      const stats = await dlq.getStats();

      expect(stats.totalEntries).toBe(0);
      expect(stats.byOperation).toEqual({});
      expect(stats.oldestEntry).toBeNull();
      expect(stats.newestEntry).toBeNull();
    });
  });

  describe("alert threshold", () => {
    it("should alert when DLQ exceeds threshold", async () => {
      const dlqWithLowThreshold = createDeadLetterQueue({
        dlqPath,
        alertThreshold: 2,
      });

      let alertFired = false;
      let alertSize = 0;

      // Override the alert method for testing
      dlqWithLowThreshold.onAlert((size) => {
        alertFired = true;
        alertSize = size;
      });

      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: {},
        failureReason: "Test failure",
        retryCount: 1,
        originalError: new Error("Test"),
      };

      await dlqWithLowThreshold.enqueue(entry);
      expect(alertFired).toBe(false);

      await dlqWithLowThreshold.enqueue(entry);
      expect(alertFired).toBe(true);
      expect(alertSize).toBe(2);
    });
  });

  describe("persistence", () => {
    it("should load entries from existing DLQ file on startup", async () => {
      // Create DLQ file manually
      const entry1: DLQEntry = {
        errorId: "test-id-1",
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        failedAt: new Date().toISOString(),
        originalError: { message: "Timeout", name: "Error" },
      };

      const content = JSON.stringify(entry1) + "\n";
      await writeFile(dlqPath, content, "utf-8");

      // Create new DLQ service (should load from file)
      const dlq2 = createDeadLetterQueue({ dlqPath });
      await dlq2.start(); // Load entries from disk
      const list = await dlq2.list();

      expect(list.length).toBe(1);
      expect(list[0].errorId).toBe("test-id-1");
    });
  });

  describe("rotation and retention", () => {
    it("should rotate DLQ file when it exceeds max size", async () => {
      const tempDir = join(tmpdir(), `ao-dlq-rotation-${Date.now()}`);
      await mkdir(tempDir, { recursive: true });
      const dlqPath = join(tempDir, "dlq.jsonl");

      // Create DLQ with very small max size (1KB)
      const smallMaxSize = 1024; // 1KB
      const dlq = createDeadLetterQueue({
        dlqPath,
        alertThreshold: 1000,
        maxDlqSize: smallMaxSize,
      });

      await dlq.start();

      // Add a small entry (should not trigger rotation)
      const smallEntry: DLQEntryInput = {
        operation: "small_op",
        payload: { data: "x" },
        failureReason: "Test",
        retryCount: 1,
        originalError: new Error("Test"),
      };
      await dlq.enqueue(smallEntry);

      // File should exist and be small
      const stats1 = await stat(dlqPath);
      expect(stats1.size).toBeLessThan(smallMaxSize);

      // Add multiple large entries to exceed max size
      for (let i = 0; i < 10; i++) {
        const largeEntry: DLQEntryInput = {
          operation: `large_op_${i}`,
          payload: { data: "x".repeat(500) }, // 500 chars per entry
          failureReason: "Test failure with large payload",
          retryCount: 3,
          originalError: new Error("Large error"),
        };
        await dlq.enqueue(largeEntry);
      }

      // Rotation should have occurred - rotated file should exist
      const files = await readdir(tempDir);
      const rotatedFiles = files.filter((f) => f.startsWith("dlq.jsonl."));
      expect(rotatedFiles.length).toBeGreaterThan(0);

      await dlq.stop();

      // Cleanup
      await unlink(dlqPath).catch(() => {});
      for (const file of rotatedFiles) {
        await unlink(join(tempDir, file)).catch(() => {});
      }
      await rmdir(tempDir);
    });

    it("should clean up old rotated files beyond retention period", async () => {
      const tempDir = join(tmpdir(), `ao-dlq-retention-${Date.now()}`);
      await mkdir(tempDir, { recursive: true });
      const dlqPath = join(tempDir, "dlq.jsonl");

      // Create DLQ with 1 day retention and small max size
      const retentionDays = 1;
      const smallMaxSize = 1024; // 1KB
      const dlq = createDeadLetterQueue({
        dlqPath,
        alertThreshold: 1000,
        retentionDays,
        maxDlqSize: smallMaxSize,
      });

      await dlq.start();

      // Create some old rotated files
      const oldDate = new Date();
      oldDate.setDate(oldDate.getDate() - 3); // 3 days ago
      const oldDateStr = oldDate.toISOString().split("T")[0];

      const rotatedPath = join(tempDir, `dlq.jsonl.${oldDateStr}`);
      await writeFile(rotatedPath, JSON.stringify({ test: "old" }), "utf-8");

      // Verify old file exists
      expect(existsSync(rotatedPath)).toBe(true);

      // Add enough entries to trigger rotation (which triggers cleanup)
      for (let i = 0; i < 10; i++) {
        const entry: DLQEntryInput = {
          operation: `test_op_${i}`,
          payload: { data: "x".repeat(500) },
          failureReason: "Test",
          retryCount: 1,
          originalError: new Error("Test"),
        };
        await dlq.enqueue(entry);
      }

      // Give cleanup a moment to run
      await new Promise((resolve) => setTimeout(resolve, 100));

      // Old rotated file should have been cleaned up
      const stillExists = existsSync(rotatedPath);
      expect(stillExists).toBe(false);

      await dlq.stop();

      // Cleanup all rotated files first
      const remainingFiles = await readdir(tempDir);
      for (const file of remainingFiles) {
        await unlink(join(tempDir, file)).catch(() => {});
      }
      await rmdir(tempDir);
    });

    it("should preserve recent rotated files within retention period", async () => {
      const tempDir = join(tmpdir(), `ao-dlq-recent-${Date.now()}`);
      await mkdir(tempDir, { recursive: true });
      const dlqPath = join(tempDir, "dlq.jsonl");

      // Create DLQ with 7 day retention
      const retentionDays = 7;
      const dlq = createDeadLetterQueue({
        dlqPath,
        alertThreshold: 1000,
        retentionDays,
      });

      await dlq.start();

      // Create a recent rotated file (1 day old)
      const recentDate = new Date();
      recentDate.setDate(recentDate.getDate() - 1);
      const recentDateStr = recentDate.toISOString().split("T")[0];

      const rotatedPath = join(tempDir, `dlq.jsonl.${recentDateStr}`);
      await writeFile(rotatedPath, JSON.stringify({ test: "recent" }), "utf-8");

      // Verify recent file exists
      expect(existsSync(rotatedPath)).toBe(true);

      // Add an entry to trigger cleanup check
      const entry: DLQEntryInput = {
        operation: "test_op",
        payload: {},
        failureReason: "Test",
        retryCount: 1,
        originalError: new Error("Test"),
      };
      await dlq.enqueue(entry);

      // Give cleanup a moment to run
      await new Promise((resolve) => setTimeout(resolve, 100));

      // Recent rotated file should still exist
      const stillExists = existsSync(rotatedPath);
      expect(stillExists).toBe(true);

      await dlq.stop();

      // Cleanup
      await unlink(dlqPath).catch(() => {});
      await unlink(rotatedPath).catch(() => {});
      await rmdir(tempDir);
    });
  });
});
