/**
 * Dead Letter Queue Tests
 *
 * Test coverage for:
 * - Storing failed operations
 * - Persisting to disk (dlq.jsonl)
 * - CLI operations: list, replay, purge
 * - Alert on large queue size
 */

import { unlink, readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  createDeadLetterQueue,
  type DeadLetterQueueService,
  type DLQEntry,
} from "../dead-letter-queue.js";

// Input type for enqueue (excludes fields generated by the service)
type DLQEntryInput = Omit<DLQEntry, "errorId" | "failedAt"> & {
  originalError: Error | { message: string; name: string };
};

describe("DeadLetterQueue", () => {
  let dlq: DeadLetterQueueService;
  let dlqPath: string;

  beforeEach(async () => {
    // Create temp directory for test DLQ files
    const tempDir = join(tmpdir(), `ao-dlq-test-${Date.now()}`);
    await mkdir(tempDir, { recursive: true });
    dlqPath = join(tempDir, "dlq.jsonl");

    // Create DLQ service
    dlq = createDeadLetterQueue({
      dlqPath,
      alertThreshold: 1000,
    });
  });

  afterEach(async () => {
    // Cleanup
    if (existsSync(dlqPath)) {
      await unlink(dlqPath);
    }
  });

  describe("enqueue", () => {
    it("should store a failed operation", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const errorId = await dlq.enqueue(entry);

      expect(errorId).toBeDefined();
      expect(typeof errorId).toBe("string");

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(1);
    });

    it("should persist entry to disk", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      await dlq.enqueue(entry);

      // Verify file exists and contains entry
      expect(existsSync(dlqPath)).toBe(true);
      const content = await readFile(dlqPath, "utf-8");
      const lines = content.trim().split("\n");
      expect(lines.length).toBe(1);

      const parsed = JSON.parse(lines[0]) as DLQEntry;
      expect(parsed.operation).toBe("bmad_sync");
      expect(parsed.failureReason).toBe("Connection timeout");
    });

    it("should generate unique error IDs", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const id1 = await dlq.enqueue(entry);
      const id2 = await dlq.enqueue(entry);

      expect(id1).not.toBe(id2);
    });

    it("should store timestamp when enqueued", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const before = Date.now();
      await dlq.enqueue(entry);
      const after = Date.now();

      const list = await dlq.list();
      expect(list.length).toBe(1);

      const failedAt = new Date(list[0].failedAt).getTime();
      expect(failedAt).toBeGreaterThanOrEqual(before);
      expect(failedAt).toBeLessThanOrEqual(after);
    });
  });

  describe("list", () => {
    it("should return all failed operations", async () => {
      const entry1: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const entry2: DLQEntryInput = {
        operation: "event_publish",
        payload: { eventType: "story.update" },
        failureReason: "Service unavailable",
        retryCount: 3,
        originalError: new Error("503"),
      };

      await dlq.enqueue(entry1);
      await dlq.enqueue(entry2);

      const list = await dlq.list();
      expect(list.length).toBe(2);
      expect(list[0].operation).toBe("bmad_sync");
      expect(list[1].operation).toBe("event_publish");
    });

    it("should return empty array when no entries", async () => {
      const list = await dlq.list();
      expect(list).toEqual([]);
    });

    it("should include all entry fields", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1", data: "test" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      await dlq.enqueue(entry);
      const list = await dlq.list();

      expect(list[0]).toMatchObject({
        errorId: expect.any(String),
        operation: "bmad_sync",
        payload: { storyId: "1-1", data: "test" },
        failureReason: "Connection timeout",
        retryCount: 5,
        failedAt: expect.any(String),
      });
    });
  });

  describe("get", () => {
    it("should return entry by error ID", async () => {
      const entry: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const errorId = await dlq.enqueue(entry);
      const retrieved = await dlq.get(errorId);

      expect(retrieved).toBeDefined();
      expect(retrieved?.operation).toBe("bmad_sync");
    });

    it("should return null for non-existent error ID", async () => {
      const retrieved = await dlq.get("non-existent-id");
      expect(retrieved).toBeNull();
    });
  });

  describe("replay", () => {
    it("should execute operation and remove from DLQ on success", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);
      let executed = false;
      let receivedPayload: unknown = null;

      const replayFn = async (payload: unknown) => {
        executed = true;
        receivedPayload = payload;
        return "success";
      };

      const result = await dlq.replay(errorId, replayFn);

      expect(result).toBe("success");
      expect(executed).toBe(true);
      expect(receivedPayload).toEqual({ value: 42 });

      // Entry should be removed from DLQ
      const retrieved = await dlq.get(errorId);
      expect(retrieved).toBeNull();

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(0);
    });

    it("should keep entry in DLQ on replay failure", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);

      const replayFn = async () => {
        throw new Error("Replay failed");
      };

      const result = await dlq.replay(errorId, replayFn);
      expect(result).toBeNull(); // Replay failure returns null

      // Entry should still be in DLQ
      const retrieved = await dlq.get(errorId);
      expect(retrieved).toBeDefined();

      const stats = await dlq.getStats();
      expect(stats.totalEntries).toBe(1);
    });

    it("should return null for non-existent error ID", async () => {
      const replayFn = async () => "success";
      const result = await dlq.replay("non-existent-id", replayFn);
      expect(result).toBeNull();
    });

    it("should bypass circuit breaker when replaying", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: { value: 42 },
        failureReason: "Previous failure",
        retryCount: 3,
        originalError: new Error("Failed"),
      };

      const errorId = await dlq.enqueue(entry);

      let bypassedCircuitBreaker = false;
      const replayFn = async () => {
        bypassedCircuitBreaker = true;
        return "success";
      };

      await dlq.replay(errorId, replayFn);

      expect(bypassedCircuitBreaker).toBe(true);
    });
  });

  describe("purge", () => {
    it("should remove entries older than threshold", async () => {
      const oldEntry: DLQEntryInput = {
        operation: "old_operation",
        payload: {},
        failureReason: "Old failure",
        retryCount: 1,
        originalError: new Error("Old"),
      };

      await dlq.enqueue(oldEntry);

      // Wait a bit to ensure time difference
      await new Promise((resolve) => setTimeout(resolve, 10));

      const newEntry: DLQEntryInput = {
        operation: "new_operation",
        payload: {},
        failureReason: "New failure",
        retryCount: 1,
        originalError: new Error("New"),
      };

      await dlq.enqueue(newEntry);

      // Purge entries older than 1ms (should keep only new entry)
      const purged = await dlq.purge(1);

      expect(purged).toBe(1);

      const list = await dlq.list();
      expect(list.length).toBe(1);
      expect(list[0].operation).toBe("new_operation");
    });

    it("should return 0 when no entries to purge", async () => {
      const purged = await dlq.purge(1000);
      expect(purged).toBe(0);
    });

    it("should remove all entries if all are old", async () => {
      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: {},
        failureReason: "Test failure",
        retryCount: 1,
        originalError: new Error("Test"),
      };

      await dlq.enqueue(entry);

      // Wait to ensure entry is old enough
      await new Promise((resolve) => setTimeout(resolve, 10));

      const purged = await dlq.purge(1);

      expect(purged).toBe(1);

      const list = await dlq.list();
      expect(list.length).toBe(0);
    });
  });

  describe("getStats", () => {
    it("should return statistics about DLQ", async () => {
      const entry1: DLQEntryInput = {
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        originalError: new Error("Timeout"),
      };

      const entry2: DLQEntryInput = {
        operation: "event_publish",
        payload: { eventType: "story.update" },
        failureReason: "Service unavailable",
        retryCount: 3,
        originalError: new Error("503"),
      };

      await dlq.enqueue(entry1);
      await dlq.enqueue(entry2);

      const stats = await dlq.getStats();

      expect(stats.totalEntries).toBe(2);
      expect(stats.byOperation).toEqual({
        bmad_sync: 1,
        event_publish: 1,
      });
      expect(stats.oldestEntry).toBeDefined();
      expect(stats.newestEntry).toBeDefined();
    });

    it("should return zero stats when empty", async () => {
      const stats = await dlq.getStats();

      expect(stats.totalEntries).toBe(0);
      expect(stats.byOperation).toEqual({});
      expect(stats.oldestEntry).toBeNull();
      expect(stats.newestEntry).toBeNull();
    });
  });

  describe("alert threshold", () => {
    it("should alert when DLQ exceeds threshold", async () => {
      const dlqWithLowThreshold = createDeadLetterQueue({
        dlqPath,
        alertThreshold: 2,
      });

      let alertFired = false;
      let alertSize = 0;

      // Override the alert method for testing
      dlqWithLowThreshold.onAlert((size) => {
        alertFired = true;
        alertSize = size;
      });

      const entry: DLQEntryInput = {
        operation: "test_operation",
        payload: {},
        failureReason: "Test failure",
        retryCount: 1,
        originalError: new Error("Test"),
      };

      await dlqWithLowThreshold.enqueue(entry);
      expect(alertFired).toBe(false);

      await dlqWithLowThreshold.enqueue(entry);
      expect(alertFired).toBe(true);
      expect(alertSize).toBe(2);
    });
  });

  describe("persistence", () => {
    it("should load entries from existing DLQ file on startup", async () => {
      // Create DLQ file manually
      const entry1: DLQEntry = {
        errorId: "test-id-1",
        operation: "bmad_sync",
        payload: { storyId: "1-1" },
        failureReason: "Connection timeout",
        retryCount: 5,
        failedAt: new Date().toISOString(),
        originalError: { message: "Timeout", name: "Error" },
      };

      const content = JSON.stringify(entry1) + "\n";
      await writeFile(dlqPath, content, "utf-8");

      // Create new DLQ service (should load from file)
      const dlq2 = createDeadLetterQueue({ dlqPath });
      await dlq2.start(); // Load entries from disk
      const list = await dlq2.list();

      expect(list.length).toBe(1);
      expect(list[0].errorId).toBe("test-id-1");
    });
  });
});
