#!/usr/bin/env node

import { Command } from "commander";
import { registerInit } from "./commands/init.js";
import { registerStoryStatus } from "./commands/story-status.js";
import { registerSpawn, registerBatchSpawn } from "./commands/spawn.js";
import { registerSession } from "./commands/session.js";
import { registerSpawnStory } from "./commands/spawn-story.js";
import { registerPause } from "./commands/pause.js";
import { registerResume } from "./commands/resume.js";
import { registerAgent } from "./commands/agent.js";
import { registerAssign } from "./commands/assign.js";
import { registerSend } from "./commands/send.js";
import { registerReviewCheck } from "./commands/review-check.js";
import { registerDashboard } from "./commands/dashboard.js";
import { registerOpen } from "./commands/open.js";
import { registerStories } from "./commands/stories.js";
import { registerSprint } from "./commands/sprint.js";
import { registerEpic } from "./commands/epic.js";
import { registerFleet } from "./commands/fleet.js";
import { registerMetrics } from "./commands/metrics.js";
import { registerHealth } from "./commands/health.js";
import { registerRetro } from "./commands/retro.js";
import { registerStory } from "./commands/story.js";
import { registerStart, registerStop } from "./commands/start.js";
import { registerCreate } from "./commands/create.js";
import { registerSprintConfig } from "./commands/sprint-config.js";
import { registerVelocity } from "./commands/velocity.js";
import { registerPlan } from "./commands/plan.js";
import { registerNotifications } from "./commands/notifications.js";
import { registerSprintStart } from "./commands/sprint-start.js";
import { registerSprintEnd } from "./commands/sprint-end.js";
import { registerPoints } from "./commands/points.js";
import { registerMove } from "./commands/move.js";
import { registerSprintSummary } from "./commands/sprint-summary.js";
import { registerHistory } from "./commands/history.js";
import { registerThroughput } from "./commands/throughput.js";
import { registerCfd } from "./commands/cfd.js";
import { registerAging } from "./commands/aging.js";
import { registerCompare } from "./commands/compare.js";
import { registerWorkload } from "./commands/workload.js";
import { registerRework } from "./commands/rework.js";
import { registerMonteCarlo } from "./commands/monte-carlo.js";
import { registerNotify } from "./commands/notify.js";
import { registerDeps } from "./commands/deps.js";
import { registerGoals } from "./commands/goals.js";
import { registerSprintPlan } from "./commands/sprint-plan.js";
import { registerResolveConflicts } from "./commands/resolve-conflicts.js";
import { registerSync } from "./commands/sync.js";
import { registerErrors } from "./commands/errors.js";
import { registerRetry } from "./commands/retry.js";

const program = new Command();

program
  .name("ao")
  .description("Agent Orchestrator — manage parallel AI coding agents")
  .version("0.1.0");

registerInit(program);
registerStart(program);
registerStop(program);
registerStoryStatus(program);
registerSpawn(program);
registerBatchSpawn(program);
registerSpawnStory(program);
registerPause(program);
registerResume(program);
registerAgent(program);
registerAssign(program);
registerSession(program);
registerSend(program);
registerReviewCheck(program);
registerDashboard(program);
registerOpen(program);
registerStories(program);
registerSprint(program);
registerEpic(program);
registerFleet(program);
registerMetrics(program);
registerHealth(program);
registerRetro(program);
registerStory(program);
registerCreate(program);
registerSprintConfig(program);
registerVelocity(program);
registerPlan(program);
registerNotifications(program);
registerSprintStart(program);
registerSprintEnd(program);
registerPoints(program);
registerMove(program);
registerSprintSummary(program);
registerHistory(program);
registerThroughput(program);
registerCfd(program);
registerAging(program);
registerCompare(program);
registerWorkload(program);
registerRework(program);
registerMonteCarlo(program);
registerNotify(program);
registerNotifications(program);
registerDeps(program);
registerGoals(program);
registerSprintPlan(program);
registerResolveConflicts(program);
registerSync(program);

registerErrors(program);
registerRetry(program);

program.parse();
